import streamlit as st
import pandas as pd
import requests
from io import StringIO
from datetime import datetime

st.set_page_config(
    page_title="SafeRoad",
    page_icon="🚗",
    layout="wide"
)

# =========================================================
# CONFIG
# =========================================================

# INCOLLA QUI L'URL CSV ESATTO GENERATO DA ESPLORADATI ISTAT
# ESEMPIO FORMATO:
# https://esploradati.istat.it/SDMXWS/rest/data/41_270_DF_DCIS_MORTIFERITISTR1_1/CHIAVE_ESATTA?startPeriod=2024-01&endPeriod=2024-12
ISTAT_CSV_URL = "https://esploradati.istat.it/SDMXWS/rest/data/IT1,41_270_DF_DCIS_MORTIFERITISTR1_1,1.0/A..KILLINJ........99/ALL/?detail=full&startPeriod=2024-01-01&endPeriod=2024-12-31&dimensionAtObservation=TIME_PERIOD&format=csv"

HEADERS = {
    "Accept": "application/vnd.sdmx.data+csv;version=1.0.0"
}

# Se i nomi colonna reali sono diversi, aggiornali qui dopo aver visto il debug
COLUMN_MAPPING = {
    "TIME_PERIOD": "time_period",
    "OBS_VALUE": "value",
    "REF_AREA": "ref_area",
    "FREQ": "freq",
    "AGE": "age_group",
    "ETA": "age_group",
    "SEX": "sex",
    "SESSO": "sex",
    "ROLE": "role",
    "RUOLO": "role",
    "USER_TYPE": "role",
    "TIPO_UTENTE": "role",
    "MEASURE": "measure",
    "MISURA": "measure",
    "UNIT_MEASURE": "unit_measure",
    "PROVINCE": "province",
    "TERRITORY": "province",
    "REF_AREA_LABEL": "province"
}

MONTH_ORDER = [
    "2024-01", "2024-02", "2024-03", "2024-04", "2024-05", "2024-06",
    "2024-07", "2024-08", "2024-09", "2024-10", "2024-11", "2024-12"
]

MONTH_LABELS = {
    "All Months": "All Months",
    "2024-01": "January",
    "2024-02": "February",
    "2024-03": "March",
    "2024-04": "April",
    "2024-05": "May",
    "2024-06": "June",
    "2024-07": "July",
    "2024-08": "August",
    "2024-09": "September",
    "2024-10": "October",
    "2024-11": "November",
    "2024-12": "December",
}

# =========================================================
# DATA LOADING
# =========================================================
@st.cache_data(ttl=3600)
def fetch_istat_csv():
    if ISTAT_CSV_URL == "PASTE_ISTAT_CSV_URL_HERE":
        raise ValueError("Please paste the exact ISTAT CSV URL generated by EsploraDati.")

    r = requests.get(ISTAT_CSV_URL, headers=HEADERS, timeout=30)
    r.raise_for_status()

    text = r.text.strip()
    if not text:
        raise ValueError("Empty response from ISTAT API.")

    df = pd.read_csv(StringIO(text))
    return df

def normalize_columns(df: pd.DataFrame) -> pd.DataFrame:
    cols = {}
    for c in df.columns:
        c_clean = c.strip().upper()
        cols[c] = COLUMN_MAPPING.get(c_clean, c.strip().lower())
    df = df.rename(columns=cols)
    return df

def ensure_time_period_str(df: pd.DataFrame) -> pd.DataFrame:
    if "time_period" in df.columns:
        df["time_period"] = df["time_period"].astype(str)
    return df

def ensure_numeric_value(df: pd.DataFrame) -> pd.DataFrame:
    if "value" in df.columns:
        df["value"] = pd.to_numeric(df["value"], errors="coerce")
    return df

def filter_2024(df: pd.DataFrame) -> pd.DataFrame:
    if "time_period" in df.columns:
        df = df[df["time_period"].astype(str).str.startswith("2024")]
    return df

def get_dimension_values(df, col):
    if col not in df.columns:
        return []
    return sorted(df[col].dropna().astype(str).unique().tolist())

def pick_geo_column(df):
    for candidate in ["province", "ref_area"]:
        if candidate in df.columns:
            return candidate
    return None

def pivot_measure_table(df, index_cols):
    if "measure" in df.columns and "value" in df.columns:
        out = df.pivot_table(
            index=index_cols,
            columns="measure",
            values="value",
            aggfunc="sum",
            fill_value=0
        ).reset_index()
        out.columns = [str(c) for c in out.columns]
        return out
    return None

# =========================================================
# LOAD DATA
# =========================================================
st.title("🚗 SafeRoad")
st.caption("Insurance Risk Assessment Dashboard | Live ISTAT SDMX Data Only")

try:
    raw_df = fetch_istat_csv()
    df = normalize_columns(raw_df)
    df = ensure_time_period_str(df)
    df = ensure_numeric_value(df)
    df = filter_2024(df)
except Exception as e:
    st.error("Unable to load ISTAT live data.")
    st.code(str(e))
    st.stop()

if df.empty:
    st.error("The ISTAT API returned no rows for 2024.")
    st.stop()

geo_col = pick_geo_column(df)

st.success("Live ISTAT data loaded")
st.caption(f"Last update: {datetime.now().strftime('%d/%m/%Y %H:%M')}")

# =========================================================
# SIDEBAR
# =========================================================
st.sidebar.header("Filters")

if geo_col:
    geo_values = get_dimension_values(df, geo_col)
    default_geo = geo_values[:5] if len(geo_values) >= 5 else geo_values
    selected_geo = st.sidebar.multiselect(
        "Province / Area",
        options=geo_values,
        default=default_geo
    )
else:
    selected_geo = []

month_values = [m for m in MONTH_ORDER if m in get_dimension_values(df, "time_period")]
selected_month = st.sidebar.selectbox(
    "Month",
    options=["All Months"] + month_values,
    format_func=lambda x: MONTH_LABELS.get(x, x)
)

age_values = get_dimension_values(df, "age_group")
selected_age = st.sidebar.selectbox(
    "Age Group",
    options=["All Ages"] + age_values if age_values else ["All Ages"]
)

role_values = get_dimension_values(df, "role")
selected_role = st.sidebar.selectbox(
    "Role",
    options=["All Roles"] + role_values if role_values else ["All Roles"]
)

measure_values = get_dimension_values(df, "measure")
selected_measures = st.sidebar.multiselect(
    "Measures",
    options=measure_values,
    default=measure_values[:6] if len(measure_values) >= 6 else measure_values
)

st.sidebar.markdown("---")
st.sidebar.caption("Source: ISTAT SDMX REST")
st.sidebar.caption("Year: 2024 only")

# =========================================================
# FILTER DATA
# =========================================================
df_f = df.copy()

if geo_col and selected_geo:
    df_f = df_f[df_f[geo_col].astype(str).isin(selected_geo)]

if selected_month != "All Months" and "time_period" in df_f.columns:
    df_f = df_f[df_f["time_period"].astype(str) == selected_month]

if selected_age != "All Ages" and "age_group" in df_f.columns:
    df_f = df_f[df_f["age_group"].astype(str) == selected_age]

if selected_role != "All Roles" and "role" in df_f.columns:
    df_f = df_f[df_f["role"].astype(str) == selected_role]

if selected_measures and "measure" in df_f.columns:
    df_f = df_f[df_f["measure"].astype(str).isin(selected_measures)]

if df_f.empty:
    st.warning("No rows match the selected filters.")
    st.stop()

# =========================================================
# KPI AREA
# =========================================================
st.markdown("## Summary")

total_value = df_f["value"].sum() if "value" in df_f.columns else 0
obs_count = len(df_f)
distinct_geo = df_f[geo_col].nunique() if geo_col else 0
distinct_measures = df_f["measure"].nunique() if "measure" in df_f.columns else 0

k1, k2, k3, k4 = st.columns(4)
k1.metric("Total value", f"{total_value:,.0f}")
k2.metric("Observations", f"{obs_count:,}")
k3.metric("Areas", f"{distinct_geo:,}")
k4.metric("Measures", f"{distinct_measures:,}")

# =========================================================
# MEASURE SUMMARY
# =========================================================
if "measure" in df_f.columns and "value" in df_f.columns:
    st.markdown("## Measure totals")
    measure_summary = (
        df_f.groupby("measure", dropna=False)["value"]
        .sum()
        .sort_values(ascending=False)
    )
    st.bar_chart(measure_summary)

# =========================================================
# MONTHLY TREND
# =========================================================
if "time_period" in df_f.columns and "value" in df_f.columns:
    st.markdown("## Monthly trend")
    if "measure" in df_f.columns:
        trend_measure = st.selectbox(
            "Trend measure",
            options=get_dimension_values(df_f, "measure")
        )
        trend_df = df_f[df_f["measure"].astype(str) == trend_measure].copy()
    else:
        trend_df = df_f.copy()

    trend = (
        trend_df.groupby("time_period")["value"]
        .sum()
        .reindex(month_values)
    )
    st.line_chart(trend)

# =========================================================
# AGE COMPARISON
# =========================================================
if "age_group" in df_f.columns and "value" in df_f.columns:
    st.markdown("## Age group comparison")
    age_compare = df_f.groupby("age_group")["value"].sum().sort_values(ascending=False)
    st.bar_chart(age_compare)

# =========================================================
# ROLE COMPARISON
# =========================================================
if "role" in df_f.columns and "value" in df_f.columns:
    st.markdown("## Role comparison")
    role_compare = df_f.groupby("role")["value"].sum().sort_values(ascending=False)
    st.bar_chart(role_compare)

# =========================================================
# AREA COMPARISON
# =========================================================
if geo_col and "value" in df_f.columns:
    st.markdown("## Area comparison")
    area_compare = df_f.groupby(geo_col)["value"].sum().sort_values(ascending=False)
    st.bar_chart(area_compare)

# =========================================================
# PIVOT TABLE
# =========================================================
st.markdown("## Pivot view")

index_cols = []
for c in [geo_col, "time_period", "age_group", "role"]:
    if c and c in df_f.columns:
        index_cols.append(c)

pivot_df = pivot_measure_table(df_f, index_cols=index_cols)

if pivot_df is not None:
    st.dataframe(pivot_df, use_container_width=True)
else:
    st.dataframe(df_f, use_container_width=True)

# =========================================================
# DEBUG SECTION
# =========================================================
with st.expander("Debug: raw ISTAT columns"):
    st.write(df.columns.tolist())
    st.dataframe(df.head(20), use_container_width=True)

# =========================================================
# DOWNLOAD
# =========================================================
csv = df_f.to_csv(index=False).encode("utf-8")
st.download_button(
    "Download filtered CSV",
    data=csv,
    file_name="saferoad_istat_2024.csv",
    mime="text/csv"
)